workflows:
  android-workflow:
    name: PlayTVNow Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Baixar pacotes do Flutter
        script: |
          flutter packages pub get
      - name: Gerar Ícone da Aplicação
        script: |
          flutter pub run flutter_launcher_icons
      - name: Construir o APK e AAB
        script: |
          flutter build apk --release --split-per-abi
          flutter build appbundle --release
      - name: Assinatura Permanente (A Magia Acontece Aqui)
        script: |
          # 1. Verifica se a chave já existe no GitHub
          if [ -f "playtvnow.keystore" ]; then
            echo "Chave permanente encontrada no GitHub! A proteger o aplicativo..."
          else
            echo "Chave não encontrada. A gerar a sua Chave Permanente oficial..."
            keytool -genkey -v -keystore playtvnow.keystore -alias playtvnow -keyalg RSA -keysize 2048 -validity 10000 -storepass "jinoca2026" -keypass "jinoca2026" -dname "CN=PlayTVNow, OU=PlayTVNow, O=PlayTVNow, L=Maputo, ST=Maputo, C=MZ"
          fi
          
          # 2. Assina o AAB (Para a Google Play)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore playtvnow.keystore -storepass "jinoca2026" build/app/outputs/bundle/release/app-release.aab playtvnow
          
          # 3. Assina os APKs (Para instalar direto no telemóvel)
          APKSIGNER=$(ls -d /usr/local/share/android-sdk/build-tools/*/apksigner | sort -r | head -n 1)
          for apk in build/app/outputs/flutter-apk/*-release.apk; do
            $APKSIGNER sign --ks playtvnow.keystore --ks-pass pass:jinoca2026 "$apk"
          done
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/app-release.aab
      - playtvnow.keystore # Exporta a chave para você fazer o download!
